#!/bin/sh
# Copyright (C) 2022 Deokgyu Yang

# Copyright (C) 2026 Sam Bélanger

set -e

NAME=killer-e3100
VERSION=1.0.1

msg() {
	echo "killer-e3100-dkms: $@"
}

case "$1" in
    remove|upgrade|deconfigure)
      if [  "`dkms status -m $NAME`" ]; then
         dkms remove -m $NAME -v $VERSION --all
      fi
    ;;

    failed-upgrade)
    ;;

    *)
        msg "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac



exit 0
